name: CI, Coverage & Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      runTest:
        description: 'Run tests before publishing'
        required: false
        default: true
        type: boolean

jobs:
  test-and-coverage:
    if: ${{ inputs.runTest != false }}
    name: Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # importante per Codecov sulle PR

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint & Pre-test
        run: npm run pretest

      - name: Run tests
        run: npm test

      - name: Print Coverage
        run: npm run coverage:report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          flags: unittests
          name: codecov-coverage
          fail_ci_if_error: true

  publish-gpr:
    needs: test-and-coverage
    if: ${{ always() && (needs.test-and-coverage.result == 'success' || needs.test-and-coverage.result == 'skipped') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm publish

